# daemon runs in the background
# run something like tail /var/log/Spitchd/current to see the status
# be sure to run with volumes, ie:
# docker run -v $(pwd)/Spitchd:/var/lib/Spitchd -v $(pwd)/wallet:/home/Spitch --rm -ti Spitch:latest
FROM ubuntu:16.04

ADD https://github.com/just-containers/s6-overlay/releases/download/v1.21.2.2/s6-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-amd64.tar.gz -C /

ADD https://github.com/just-containers/socklog-overlay/releases/download/v2.1.0-0/socklog-overlay-amd64.tar.gz /tmp/
RUN tar xzf /tmp/socklog-overlay-amd64.tar.gz -C /

COPY . /src/Spitch


# install build dependencies
# checkout the latest tag
# build and install
RUN apt-get update && \
    apt-get install -y \
      build-essential \
      python-dev \
      gcc-4.9 \
      g++-4.9 \
      git cmake \
      libboost1.58-all-dev && \
    cd /src/Spitch && \
    mkdir build && \
    cd build && \
    cmake -DCMAKE_CXX_FLAGS="-g0 -Os -fPIC -std=gnu++11" .. && \
    make -j$(nproc) && \
    mkdir -p /usr/local/bin && \
    cp src/Spitchd /usr/local/bin/Spitchd && \
    cp src/walletd /usr/local/bin/walletd && \
    cp src/zedwallet /usr/local/bin/zedwallet && \
    cp src/miner /usr/local/bin/miner && \
    strip /usr/local/bin/Spitchd && \
    strip /usr/local/bin/walletd && \
    strip /usr/local/bin/zedwallet && \
    strip /usr/local/bin/miner && \
    cd / && \
    rm -rf /src/Spitch && \
    apt-get remove -y build-essential python-dev gcc-4.9 g++-4.9 git cmake libboost1.58-all-dev && \
    apt-get autoremove -y && \
    apt-get install -y  \
      libboost-system1.58.0 \
      libboost-filesystem1.58.0 \
      libboost-thread1.58.0 \
      libboost-date-time1.58.0 \
      libboost-chrono1.58.0 \
      libboost-regex1.58.0 \
      libboost-serialization1.58.0 \
      libboost-program-options1.58.0 \
      libicu55

# setup the Spitchd service
RUN useradd -r -s /usr/sbin/nologin -m -d /var/lib/Spitchd Spitchd && \
    useradd -s /bin/bash -m -d /home/Spitch Spitch && \
    mkdir -p /etc/services.d/Spitchd/log && \
    mkdir -p /var/log/Spitchd && \
    echo "#!/usr/bin/execlineb" > /etc/services.d/Spitchd/run && \
    echo "fdmove -c 2 1" >> /etc/services.d/Spitchd/run && \
    echo "cd /var/lib/Spitchd" >> /etc/services.d/Spitchd/run && \
    echo "export HOME /var/lib/Spitchd" >> /etc/services.d/Spitchd/run && \
    echo "s6-setuidgid Spitchd /usr/local/bin/Spitchd" >> /etc/services.d/Spitchd/run && \
    chmod +x /etc/services.d/Spitchd/run && \
    chown nobody:nogroup /var/log/Spitchd && \
    echo "#!/usr/bin/execlineb" > /etc/services.d/Spitchd/log/run && \
    echo "s6-setuidgid nobody" >> /etc/services.d/Spitchd/log/run && \
    echo "s6-log -bp -- n20 s1000000 /var/log/Spitchd" >> /etc/services.d/Spitchd/log/run && \
    chmod +x /etc/services.d/Spitchd/log/run && \
    echo "/var/lib/Spitchd true Spitchd 0644 0755" > /etc/fix-attrs.d/Spitchd-home && \
    echo "/home/Spitch true Spitch 0644 0755" > /etc/fix-attrs.d/Spitch-home && \
    echo "/var/log/Spitchd true nobody 0644 0755" > /etc/fix-attrs.d/Spitchd-logs

VOLUME ["/var/lib/Spitchd", "/home/Spitch","/var/log/Spitchd"]

ENTRYPOINT ["/init"]
CMD ["/usr/bin/execlineb", "-P", "-c", "emptyenv cd /home/Spitch export HOME /home/Spitch s6-setuidgid Spitch /bin/bash"]
